# .github/workflows/deploy.yml
name: Deploy presets.json
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Build presets.json
        run: yarn build
      - name: Commit presets.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: github.com/ChatHubLab/awesome-chathub-presets
        run: |
          rm .gitignore
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com' 
          git checkout -b preset
          git add presets.json
          git commit -m "Deploy $GITHUB_SHA"
          git push --force --quiet "https://$GH_TOKEN@$REPO"
